title: Matt Wamboldt
tagline: Web and Game Developer Portfolio
author: Matt Wamboldt
email: mattwamboldt@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  From high level to low level, TypeScript to Assembly, I've done a lot.
  Let's learn and experience the wide world of Software Development together!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mattwamboldt
github_username:  mattwamboldt
linkedin_username: mattwamboldt

show_excerpts: true
collections:
  projects:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

paginate: 10
paginate_path: "/blog/:num/"
permalink: /blog/:year-:month-:day/:title

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
